x-common-env: &common-env
  DB_USER: ${DB_USER:-admin}
  DB_PASSWORD: ${DB_PASSWORD:-admin123}
  DB_HOST: ${DB_HOST:-127.0.0.1}
  RABBIT_USER: ${RABBIT_USER:-guest}
  RABBIT_PASSWORD: ${RABBIT_PASSWORD:-guest}
  ENCRYPTION_KEY: ${ENCRYPTION_KEY:-uwAdrr58WR0vTST0mLh2XyE-qV6uroWkv0MLHuzVW6g=}
  CELERY_BROKER_URL: ${CELERY_BROKER_URL:-amqp://guest:guest@127.0.0.1:5672//}
  APP_USER: ${APP_USER:-admin}
  APP_PASS: ${APP_PASS:-admin123}
  EMOTION_MODEL_NAME: ${EMOTION_MODEL_NAME:-dima806/facial_emotions_image_detection}

x-common-service: &common-service
  image: ${DOCKER_IMAGE:-ghcr.io/adrian-wozniak-wat/shere:latest}
  volumes:
    - .:/app
  network_mode: "host"
  env_file:
    - path: .env
      required: false
  environment:
    <<: *common-env

services:
  web:
    <<: *common-service
    command: web
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  celery_worker:
    <<: *common-service
    command: worker
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      web:
        condition: service_started

  celery_beat:
    <<: *common-service
    command: beat  
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      web:
        condition: service_started

  db:
    image: postgres:15
    restart: always
    network_mode: "host"
    environment:
      - POSTGRES_USER=${DB_USER:-admin}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-admin123}
      - POSTGRES_DB=ha_emotion_research
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-admin} -d ha_emotion_research"]
      interval: 3s
      timeout: 3s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    network_mode: "host"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASSWORD:-guest}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq

volumes:
  postgres_data:
  rabbitmq_data:
  rabbitmq_logs:
