# Generated by Django 6.0.6 on 2026-06-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeassistantcredentials',
            name='host',
            field=models.CharField(default='localhost', max_length=255),
        ),
        migrations.AddField(
            model_name='homeassistantcredentials',
            name='port',
            field=models.IntegerField(default=8123),
        ),
    ]
