# Generated by Django 6.0.6 on 2026-06-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_analyzer', '0002_homeassistantcredentials_host_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeassistantcredentials',
            name='_encrypted_password',
        ),
        migrations.AddField(
            model_name='homeassistantcredentials',
            name='_encrypted_token',
            field=models.TextField(db_column='encrypted_token', default=''),
            preserve_default=False,
        ),
    ]
