# Generated by Django 6.0.6 on 2026-06-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_analyzer', '0003_remove_homeassistantcredentials__encrypted_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='entity',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
