# Generated by Django 6.0.6 on 2026-07-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_analyzer', '0004_camera_name_entity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
