# Generated by Django 6.0.6 on 2026-07-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_analyzer', '0005_alter_entity_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
