# Generated by Django 6.0.6 on 2026-07-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_analyzer', '0006_alter_camera_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camerasnapshot',
            name='image',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='camera_snapshots/%Y/%m/%d/'),
        ),
    ]
