# Generated by Django 6.0.6 on 2026-09-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_analyzer', '0007_alter_camerasnapshot_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollcycle',
            name='cycle_length_milliseconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pollcycle',
            name='emotion_recognition_milliseconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pollcycle',
            name='face_recognition_milliseconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
