# Generated by Django 6.0.6 on 2026-09-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_analyzer', '0008_pollcycle_cycle_length_milliseconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerasnapshot',
            name='emotion_recognition_milliseconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camerasnapshot',
            name='face_recognition_milliseconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
